products/urls.py
from django.conf.urls import url
from products import views

urlpatterns = [
    url(r'^$', views.CategoryListView.as_view(), name='category_list'),
    url(r'^new/$', views.LastAddProductListView.as_view(), name='product_new'),
    url(r'^(?P<slug>[\w-]+)/$', views.ProductListView.as_view(), name='product_list'),
    url(r'^(?P<slug_category>[\w-]+)/(?P<slug>[\w-]+)/$', views.ProductDetailView.as_view(), name='product_detail'),
]

products_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from products import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^$', views.index, name='index'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
from __future__ import unicode_literals
from django.utils import timezone
from django.db import models
from pytils.translit import slugify
from decimal import Decimal
from django.core.validators import MinValueValidator


def slug_create(self):
    slug = slugify(self.name)
    slug_exists = True
    counter = 1
    self.slug = slug
    while slug_exists:
        try:
            slug_exits = self._meta.model.objects.get(slug=slug)
            if slug_exits:
                slug = self.slug + '_' + str(counter)
                counter += 1
        except self._meta.model.DoesNotExist:
            self.slug = slug
            break


class Category(models.Model):
    name = models.CharField(max_length=40)
    slug = models.SlugField(max_length=40, unique=True)
    description = models.TextField()

    def __unicode__(self):
        return '{0}'.format(self.name)

    def save(self, *args, **kwargs):
        if not self.id:
            slug_create(self)
        super(Category, self).save(*args, **kwargs)


class Product(models.Model):
    name = models.CharField(max_length=40)
    slug = models.SlugField(max_length=50, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category)

    def __unicode__(self):
        return '{0}'.format(self.name)

    def save(self, *args, **kwargs):
        if not self.id:
            slug_create(self)
        super(Product, self).save(*args, **kwargs)

products/views.py
from django.views.generic.list import ListView
from django.views.generic import DetailView
from django.shortcuts import render
import datetime
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404
from models import Category, Product

hours_delta = 24


def index(request):
    return render(request, 'base.html')


class CategoryListView(ListView):
    model = Category


class ProductListView(ListView):
    model = Product
    category_slug = None

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        self.category_slug = slug
        self.queryset = Product.objects.filter(category__slug=slug)
        return self.queryset

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        # category_slug = self.kwargs.get('slug')
        category = get_object_or_404(Category, slug=self.category_slug)
        context['category'] = category
        return context


class ProductDetailView(DetailView):
    model = Product
    query_pk_and_slug = True
    template_name = 'products/product_detail.html'


class LastAddProductListView(ListView):
    model = Product
    template_name = 'products/new_product_list.html'

    def get(self, request, *args, **kwargs):
        date_from = datetime.datetime.now() - datetime.timedelta(hours=hours_delta)
        new_products = Product.objects.filter(created_at__gte=date_from)
        self.queryset = new_products
        return super(LastAddProductListView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(LastAddProductListView, self).get_context_data(**kwargs)
        category_list = {}
        for product in self.object_list:
            name = product.category
            if name not in category_list:
                category_list.update({name: [product, ]})
            else:
                category_list[name].append(product)

        context['category_list'] = category_list
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LastAddProductListView, self).dispatch(*args, **kwargs)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
    {% block title %} Торты {% endblock title %}
    </title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/business-casual.css' %}" rel="stylesheet">

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="brand">Python Test Task</div>
    <div class="address-bar" >
       {% block auth %}
          {% if user.is_authenticated %}
              Logged in: {{ user.username }}
              (<a href="{% url 'auth_logout' %}?next=/">Log out</a> |
              <a href="{% url 'auth_password_change' %}">Change password</a>)
          {% else %}
             <a href="{% url 'auth_login' %}">Log in</a>
          {% endif %}

      {% endblock %}
    </div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="{% url 'index' %}">Python Test Task</a>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'products:category_list' %}">Категории</a>
                    </li>
                    <li>
                        <a href="{% url 'products:product_new' %}">Новые товары</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

    <div class="row">
        <div class="box">
          <div class="col-lg-12">
            {% if messages %}
              {% for message in messages %}
              <div class="panel panel-success">
                <div class="panel-heading">
                  <h3 class="panel-title">{{ message }}</h3>
                </div>
              </div>
              {% endfor %}
            {% endif %}

            <div class="col-lg-12">
                {% block content %}
                  <hr>
                    <h2 class="intro-text text-center">Build a website
                    </h2>
                    <hr>
                    <hr class="visible-xs">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                {% endblock %}
            </div>

          </div>
        </div>

    </div>
    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Kostenko Anna 2016</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

templates/products/category_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} Категории {% endblock title %}

{% block content %}

  {% if object_list %}
  <h2>Категории</h2>
   <table  class="table table-striped ">
    {% for category in object_list %}
      <tr>
       <td>{{ forloop.counter }}</td>
       <td class="intro-text"><a href="{% url 'products:product_list' category.slug %}">
           {{ category.name }}</a></td>
       <td>{{ category.description }}</td>
      </tr>
    {% endfor %}
  </table>
  {% else %}
    <p><br />Пока нет категорий</p>
  {% endif %}

{% endblock content %}

templates/products/new_product_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} Новые {% endblock title %}

{% block content %}

  {% if object_list and category_list %}
    {% for key, value in category_list.items %}
    <h2>{{ key.name }}</h2>
   <table  class="table table-striped ">
    <thead>
      <tr>
       <th></th><th>Имя</th><th>Цена</th><th>Описание</th>
      </tr>
    </thead>
    <tbody>
    {% for product in value %}
        <tr>
         <td>{{ forloop.counter }}</td>
         <td class="intro-text">
           <a href="{% url 'products:product_detail' product.category.slug product.slug %}">
             {{ product.name }}</a></td>
         <td>{{ product.price }}</td>
         <td>{{ product.description }}</td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
    {% endfor %}
  {% else %}
    <p><br />Пока нет продуктов</p>
  {% endif %}

{% endblock content %}

templates/products/product_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} Торт {% endblock title %}

{% block content %}

  {% if product %}
  <h2>Торт {{ product.name }} </h2>
   <table  class="table ">
      <tr>
       <td>Цена</td>
       <td class="intro-text">{{ product.price }}</td>
      </tr>
      <tr>
       <td>Описание</td>
        <td>{{ product.description }}</td>
       </tr>
  </table>
  {% else %}
    <p><br />Нет данных</p>
  {% endif %}

{% endblock content %}

templates/products/product_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

{% if category %}
  {% if object_list %}
  <h2>{{ category.name }}</h2>
   <table  class="table table-striped ">
    <thead>
      <tr>
       <th></th><th>Имя</th><th>Цена</th><th>Описание</th>
      </tr>
    </thead>
    <tbody>
    {% for product in object_list %}
      <tr>
       <td>{{ forloop.counter }}</td>
       <td class="intro-text">
         <a href="{% url 'products:product_detail' product.category.slug product.slug %}">
           {{ product.name }}</a></td>
       <td>{{ product.price }}</td>
       <td>{{ product.description }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p><br />Пока нет продуктов этой категорий</p>
  {% endif %}
{% else %}
  <p><br />Категория не найдена</p>
{% endif %}

{% endblock content %}